# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20171121_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='btitle',
            field=models.CharField(max_length=20),
        ),
    ]
