# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20171121_0817'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
            ],
        ),
    ]
